import Image from "next/image"
import Link from "next/link"
import { CheckCircle2 } from "lucide-react"
import { FOUNDING_PARTNER_OFFER, FOUNDING_VALUE_ITEMS } from "@/lib/offers/founding-partner"
import { commandMapPricingPackage } from "@/lib/pricing/source-of-truth"

type PricingSearchParams = Record<string, string | string[] | undefined>

const faqs = [
  ["Is the Founding Partner price fixed?", "$3,500 is the fixed one-time setup and $500 is the monthly founding-plan base rate for this offer. It is not shown as starting pricing."],
  ["What is locked for life?", "The $500 monthly base rate for the included founding plan stays locked for the life of that founding customer. Separately scoped add-ons are not part of the rate lock."],
  ["How does the 30-day guarantee work?", "The 30 days begin when the installed AI Office is launched for staff use. If it does not make the agreed office work meaningfully faster or better, cancel during that period for a full refund of the Installation Sprint fee."],
  ["Can Stanley change important records without approval?", "No new consequential write path or expanded permission is activated without written approval. Each accepted capability is set to read-only, prepare-only, or approval-required before launch."],
  ["Is there a direct installation checkout?", "No. The Founding Partner path starts with an application and fit review."],
  ["What if we are not ready for the installation?", "The $197 AI Office Command Map provides one bounded installed starter, two DIY kits, and three personalized office-action blueprints."],
]

export function PricingPage({ searchParams: _searchParams }: { searchParams: PricingSearchParams }) {
  return <main className="overflow-hidden bg-[#FBFCF7] text-[#071D3A]">
    <section data-nav-theme="light" className="relative isolate flex min-h-[82svh] items-center px-5 pb-20 pt-36 md:px-8 lg:px-10"><Image src="/images/uploaded/ai-office-ops/ai-office-ops-laptop-mockup-enhanced.jpg" alt="" fill priority sizes="100vw" className="-z-20 object-cover object-center opacity-50" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,#FBFCF7_0%,rgba(251,252,247,.96)_44%,rgba(251,252,247,.45)_100%),linear-gradient(0deg,#FBFCF7_0%,transparent_42%)]" /><div className="mx-auto w-full max-w-[88rem]"><div className="max-w-[820px]"><h1 className="text-balance text-[clamp(3.4rem,8vw,6.8rem)] font-extrabold leading-[.89] tracking-[-.045em]">More office capacity from the team you already have.</h1><p className="mt-6 max-w-2xl text-xl font-semibold leading-8 text-[#536173]">See the complete installation, training, controls, and managed operation before the founding price.</p><Link href="#included" className="mt-8 inline-flex min-h-14 items-center rounded-full bg-[#15803D] px-7 font-extrabold text-white">See what is included</Link></div></div></section>
    <section data-nav-theme="dark" className="bg-[#071422] px-5 py-20 text-white md:px-8 lg:px-10"><div className="mx-auto grid max-w-[88rem] gap-10 lg:grid-cols-2"><div><h2 className="text-balance text-[clamp(3rem,6vw,5.4rem)] font-extrabold leading-[.91] tracking-[-.04em]">One interface across supported office information.</h2></div><div className="text-lg font-semibold leading-8 text-white/70"><p>Stanley Systems works around supported CRM, accounting software, documents, inboxes, staff, and company knowledge. One request can create reports and files or prepare approved actions.</p><p className="mt-5">Sources, roles, permissions, approval previews, provider readback, and proof receipts keep the story honest.</p></div></div></section>
    <section id="included" data-nav-theme="light" className="scroll-mt-28 bg-[#E9F8ED] px-5 py-20 md:px-8 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-[88rem] gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><h2 className="text-balance text-[clamp(3rem,6vw,5.4rem)] font-extrabold leading-[.91] tracking-[-.04em]">The full founding installation.</h2><p className="mt-5 text-lg font-semibold leading-8 text-[#536173]">Staff training and 30 days of live optimization and AI Office Ops are included before ongoing monthly service begins.</p></div><ul className="grid gap-x-7 sm:grid-cols-2">{FOUNDING_VALUE_ITEMS.map(item => <li key={item} className="flex gap-3 border-b border-[#BFDCC8] py-4 font-bold"><CheckCircle2 className="h-5 w-5 shrink-0 text-[#15803D]" />{item}</li>)}</ul></div></section>
    <section data-nav-theme="light" className="px-5 py-20 md:px-8 lg:px-10"><div className="mx-auto max-w-[82rem] text-center"><h2 className="mx-auto max-w-5xl text-balance text-[clamp(3rem,6vw,5.5rem)] font-extrabold leading-[.91] tracking-[-.04em]">Before another roughly $60,000 office salary, install connected capacity first.</h2><p className="mx-auto mt-6 max-w-3xl text-lg font-semibold leading-8 text-[#536173]">This comparison does not claim to replace a current employee or guarantee recovered capacity.</p></div></section>
    <section id="founding-price" data-nav-theme="dark" data-analytics-view="founding_offer_viewed" className="bg-[#071422] px-5 py-20 text-white md:px-8 lg:px-10"><div className="mx-auto grid max-w-[82rem] gap-10 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><h2 className="text-balance text-[clamp(3rem,6vw,5.5rem)] font-extrabold leading-[.9] tracking-[-.04em]">Value first. Founding price second.</h2><p className="mt-5 text-lg font-semibold leading-8 text-white/68">{FOUNDING_PARTNER_OFFER.scarcityCopy}</p></div><div className="border-l border-white/15 pl-0 lg:pl-10"><p className="text-5xl font-extrabold">{FOUNDING_PARTNER_OFFER.setupPriceDisplay}</p><p className="mt-3 text-3xl font-extrabold text-[#8DF3A4]">{FOUNDING_PARTNER_OFFER.monthlyPriceDisplay}</p><p className="mt-4 font-bold text-white/70">{FOUNDING_PARTNER_OFFER.monthlyRateLock}</p><p className="mt-2 font-semibold text-white/52">30 days of live optimization and AI Office Ops included</p><Link href="/systems-installation-sprint#installation-contact" className="mt-7 inline-flex min-h-14 w-full items-center justify-center rounded-full bg-[#15803D] px-6 font-extrabold text-white">Apply for a Founding Partner Installation</Link></div></div></section>
    <section data-nav-theme="light" className="px-5 py-20 md:px-8"><div className="mx-auto grid max-w-[82rem] gap-9 rounded-[2rem] border border-[#D5E5DA] bg-white p-7 shadow-[0_22px_65px_rgba(7,29,58,.08)] md:grid-cols-[1fr_auto] md:items-center md:p-10"><div><h2 className="text-4xl font-extrabold tracking-[-.04em]">AI Office Command Map</h2><p className="mt-3 max-w-2xl font-semibold leading-7 text-[#536173]">One standardized starter installed with you, two DIY kits, and three personalized office-action blueprints.</p></div><div><p className="text-5xl font-extrabold">$197</p><a href={commandMapPricingPackage.stripePaymentLink.url} target="_blank" rel="noopener noreferrer" data-analytics-event="command_map_checkout_clicked" className="mt-5 inline-flex min-h-12 items-center rounded-full bg-[#15803D] px-6 font-extrabold text-white">Get the Command Map</a></div></div><div className="mx-auto mt-6 max-w-[82rem] text-center"><Link href="/ai-office-capacity-calculator" className="font-extrabold text-[#15803D] underline underline-offset-4">Use the AI Office Capacity Calculator</Link></div></section>
    <section data-nav-theme="light" className="bg-[#F5F9F2] px-5 py-20 md:px-8"><div className="mx-auto max-w-4xl"><h2 className="text-center text-5xl font-extrabold tracking-[-.04em]">Pricing questions.</h2><div className="mt-8 divide-y divide-[#D5E5DA] border-y border-[#D5E5DA]">{faqs.map(([q,a]) => <details key={q} className="py-5"><summary className="cursor-pointer text-xl font-extrabold">{q}</summary><p className="mt-3 font-semibold leading-7 text-[#536173]">{a}</p></details>)}</div></div></section>
  </main>
}
